### ISSUE TITLE
Bug: db is not reconnecting

### ISSUE THREAD

**Issue by finalclass** [surrealdb/surrealdb.js#203]
### Describe the bug

When surrealdb dies the library does not try to reconnect and it's not throwing (catchable) error.

### Steps to reproduce

1. Start surreal
2. Create new Surreal(), connect, signin, use...
3. stop surreal
4. start it again
5. try running some query using the `new Surreal()` instance.

This is the error:

```
error: Uncaught (in worker "") (in promise) InvalidStateError: readyState not OPEN
		this.ws?.send(JSON.stringify({ id, method, params }));
		         ^
    at WebSocket.send (ext:deno_websocket/01_websocket.js:327:13)
    at SurrealSocket.send (https://deno.land/x/surrealdb@v0.11.0/src/library/SurrealSocket.ts:133:12)
    at eventLoopTick (ext:core/01_core.js:197:13)
```

### Expected behaviour

The library either:
1. throws an error which can be caught
2. executuse "onError" hook
3. tries to reconnect

### SurrealDB version

1.0.0+20230913.54aedcd for linux on x86_64

### SurrealDB.js version

0.11.0

### Contact Details

s@finalclass.net

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oliver-oloughlin** [comment]
Reproduced using Deno 1.40.0 + Surrealdb v1.2.0 + surrealdb.js v0.11.0. The part about uncatchable errors is a major issue for me, and makes the driver unusable in my use case. It seems WebSockets in Deno are unstable and tend to lose connection at random. This bug prevents the connection from being reestablished, and crashes my program as I am unable to catch the errors and reconnect manually.

**Comment by akkie** [comment]
Same problem occurs with the latest beta version. Also, if I subscribe for the `ConnectionStatus.Error` or `ConnectionStatus.Disconnected` event, non of them gets triggered if SurrealDB is shut down. The node app gets killed because of the exception:

```
node:internal/deps/undici/undici:13178
      Error.captureStackTrace(err);
            ^

TypeError: fetch failed
    at node:internal/deps/undici/undici:13178:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async HttpEngine.rpc (file:///usr/src/app/apps/web/node_modules/.pnpm/surrealdb@1.0.0-beta.20_tslib@2.6.3_typescript@5.5.4_ws@8.18.0_bufferutil@4.0.8_utf-8-validate@6.0.4_/node_modules/surrealdb/dist/index.mjs:1:33547)
    at async Surreal.signin (file:///usr/src/app/apps/web/node_modules/.pnpm/surrealdb@1.0.0-beta.20_tslib@2.6.3_typescript@5.5.4_ws@8.18.0_bufferutil@4.0.8_utf-8-validate@6.0.4_/node_modules/surrealdb/dist/index.mjs:1:40207)
    at async Timeout.eval [as _onTimeout] (/usr/src/app/apps/web/src/lib/utils/surrealdb/db.server.ts:28:7) {
  [cause]: Error: getaddrinfo ENOTFOUND surrealdb
      at GetAddrInfoReqWrap.onlookupall [as oncomplete] (node:dns:120:26)
      at GetAddrInfoReqWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -3008,
    code: 'ENOTFOUND',
    syscall: 'getaddrinfo',
    hostname: 'surrealdb'
  }
}

Node.js v20.16.0
 ELIFECYCLE  Command failed with exit code 1.


```

**Comment by koakh** [comment]
hello

sorry for spam this, but I really need this feature implemented
is any preview/release date for this feature be implemented, 
or a temporary hack on do automatically reconnect in js sdk

thanks
