### ISSUE TITLE
When SurrealDB encounters a fatal error, it's impossible to know where it failed at (in my own code)

### ISSUE THREAD

**Issue by LuciferianInk** [surrealdb/surrealdb.js#60]
As you see from the logs below, we see a stack trace, but nowhere does my own code appear in that. I can't see which of my functions caused this error, and thus, locating the source of this error is more difficult than it should be.
```
sourceress-bot-1  | file:///app/node_modules/surrealdb.js/src/index.ts:625
sourceress-bot-1  |                     return reject(new Error(res.error.message));
sourceress-bot-1  |                  ^
sourceress-bot-1  | Error: There was a problem with the database: Specify some SQL code to execute
sourceress-bot-1  |     at Surreal._Surreal_result (file:///app/node_modules/surrealdb.js/src/index.ts:625:18)
sourceress-bot-1  |     at Surreal.<anonymous> (file:///app/node_modules/surrealdb.js/src/index.ts:424:27)
sourceress-bot-1  |     at Surreal.f (file:///app/node_modules/surrealdb.js/src/classes/emitter.ts:26:9)
sourceress-bot-1  |     at file:///app/node_modules/surrealdb.js/src/classes/emitter.ts:33:10
sourceress-bot-1  |     at Array.forEach (<anonymous>)
sourceress-bot-1  |     at Surreal.emit (file:///app/node_modules/surrealdb.js/src/classes/emitter.ts:32:20)
sourceress-bot-1  |     at Socket.<anonymous> (file:///app/node_modules/surrealdb.js/src/index.ts:222:17)
sourceress-bot-1  |     at file:///app/node_modules/surrealdb.js/src/classes/emitter.ts:33:10
sourceress-bot-1  |     at Array.forEach (<anonymous>)
sourceress-bot-1  |     at Socket.emit (file:///app/node_modules/surrealdb.js/src/classes/emitter.ts:32:20)
```

**Comment by mathe42** [comment]
It is near impossible to change that. This would need a lot mor of tracking etc. that would be a lot of overhead...

Maybe we can add a "debug" flag so you can enable that... (Basicly we would have to save `(new Error('')).stack`  for each call of a method.

**Comment by mathe42** [comment]
actualy this might be allready better with https://github.com/surrealdb/surrealdb.js/commit/ce949aeddd2b451b3b7b473705e62fbbc58e095b but that is currently not released...

**Comment by m59peacemaker** [comment]
Try running your node app with a higher stack trace limit. The default is 10 lines.

```sh
node --stack-trace-limit=50
```

**Comment by kearfy** [comment]
@LuciferianInk once PR #95 is merged and release this should be a lot easier:
```
file:///Users/michavries/Development/SurrealDB/surrealdb.js/npm/esm/strategies/websocket.js:169
            throw new Error(res.error.message);
                  ^

Error: There was a problem with the database: Specify some SQL code to execute
    at WebSocketStrategy.query (file:///Users/michavries/Development/SurrealDB/surrealdb.js/npm/esm/strategies/websocket.js:169:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async default (file:///Users/michavries/Development/SurrealDB/surrealdb.js/test/e2e/shared.js:115:2)
    at async file:///Users/michavries/Development/SurrealDB/surrealdb.js/test/e2e/node.js:6:1
```

In this scenario, the following line is where the `.query()` function is being executed with an empty query:
```
at async default (file:///Users/michavries/Development/SurrealDB/surrealdb.js/test/e2e/shared.js:115:2)
```

Does that solve your problem?

**Comment by kearfy** [comment]
Hi, we have shipped improvements for this a while ago, but haven't gotten a confirmation back from you. Will close this as fixed!
