### ISSUE TITLE
When used in tests I get "leaking async ops"

### ISSUE THREAD

**Issue by finalclass** [surrealdb/surrealdb.js#93]
Specifically this is what I'm having:

```
error: AssertionError: Test case is leaking async ops.

 - 1 async operation to sleep for a duration was started in this test, but never completed. This is often caused by not cancelling a `setTimeout` or `setInterval` call.
 - 1 async operation to receive the next message on a WebSocket was started in this test, but never completed. This is often caused by not closing a `WebSocket` or `WebSocketStream`.

```

I'm calling db.close() in the `afterAll` callback and I can confirm that the `db.close()` executes however it still lefts some async ops not finished.

**Comment by kearfy** [comment]
Heya, I'm refactoring the whole websocket bit in #95. Which package are you using for testing and could you get me a reproducable example? Would be much appreciated!

**Comment by finalclass** [comment]
Sure, all is needed is a usage of Surreal in deno tests. Here is a minimalistic example:

```ts
import { afterAll, beforeAll, describe, it } from "https://deno.land/std@0.185.0/testing/bdd.ts";
import { Surreal } from "https://deno.land/x/surrealdb@v0.6.0/mod.ts";
import {assert,} from "https://deno.land/std@0.185.0/testing/asserts.ts";

describe("SurrealDB", () => {

    it("does not lead async ops", async () => {
        const db = await new Surreal("http://0.0.0.0:8000/rpc");
        
        await db.signin({
            user: "root",
            pass: "root"
        });
        await db.wait();
        await db.use("test", "test");

        await db.close();
        assert(true);
    });
    
});
```

This produces the error:
```
$ deno test -A --trace-ops mod_test.ts 
running 1 test from ./mod_test.ts
SurrealDB ...
  does not lead async ops ... FAILED (54ms)
    error: AssertionError: Test case is leaking async ops.
    
     - 1 async operation to sleep for a duration was started in this test, but never completed. This is often caused by not cancelling a `setTimeout` or `setInterval` call. The operation was started here:
        at handleOpCallTracing (internal:core/01_core.js:237:42)
        at Object.op_sleep (eval at genAsyncOp (internal:core/01_core.js:181:14), <anonymous>:15:21)
        at Object.opAsync (internal:core/01_core.js:249:12)
        at runAfterTimeout (internal:ext/web/02_timers.js:219:31)
        at initializeTimer (internal:ext/web/02_timers.js:185:5)
        at setInterval (internal:ext/web/02_timers.js:329:12)
        at Pinger.start (https://deno.land/x/surrealdb@v0.6.0/src/classes/pinger.ts:12:18)
        at Socket.<anonymous> (https://deno.land/x/surrealdb@v0.6.0/src/index.ts:222:17)
        at https://deno.land/x/surrealdb@v0.6.0/src/classes/emitter.ts:62:13
        at Set.forEach (<anonymous>)
     - 1 async operation to receive the next message on a WebSocket was started in this test, but never completed. This is often caused by not closing a `WebSocket` or `WebSocketStream`. The operation was started here:
        at handleOpCallTracing (internal:core/01_core.js:237:42)
        at Object.op_ws_next_event (eval at genAsyncOp (internal:core/01_core.js:181:14), <anonymous>:15:21)
        at Object.opAsync (internal:core/01_core.js:249:12)
        at WebSocket.[[[eventLoop]]] (internal:ext/websocket/01_websocket.js:405:44)
    
          await t.step(options);
          ^
        at assert (internal:ext/web/00_infra.js:295:13)
        at asyncOpSanitizer (internal:cli/js/40_testing.js:233:13)
        at async resourceSanitizer (internal:cli/js/40_testing.js:378:7)
        at async exitSanitizer (internal:cli/js/40_testing.js:435:9)
        at async TestContext.step (internal:cli/js/40_testing.js:1355:13)
        at async Function.run (https://deno.land/std@0.185.0/testing/_test_suite.ts:323:7)
        at async fn (https://deno.land/std@0.185.0/testing/_test_suite.ts:140:15)
SurrealDB ... FAILED (62ms)

 ERRORS 

SurrealDB => https://deno.land/std@0.185.0/testing/_test_suite.ts:191:10
error: AssertionError: Test case is leaking async ops.

 - 1 async operation to sleep for a duration was started in this test, but never completed. This is often caused by not cancelling a `setTimeout` or `setInterval` call. The operation was started here:
    at handleOpCallTracing (internal:core/01_core.js:237:42)
    at Object.op_sleep (eval at genAsyncOp (internal:core/01_core.js:181:14), <anonymous>:15:21)
    at Object.opAsync (internal:core/01_core.js:249:12)
    at runAfterTimeout (internal:ext/web/02_timers.js:219:31)
    at initializeTimer (internal:ext/web/02_timers.js:185:5)
    at setInterval (internal:ext/web/02_timers.js:329:12)
    at Pinger.start (https://deno.land/x/surrealdb@v0.6.0/src/classes/pinger.ts:12:18)
    at Socket.<anonymous> (https://deno.land/x/surrealdb@v0.6.0/src/index.ts:222:17)
    at https://deno.land/x/surrealdb@v0.6.0/src/classes/emitter.ts:62:13
    at Set.forEach (<anonymous>)
 - 1 async operation to receive the next message on a WebSocket was started in this test, but never completed. This is often caused by not closing a `WebSocket` or `WebSocketStream`. The operation was started here:
    at handleOpCallTracing (internal:core/01_core.js:237:42)
    at Object.op_ws_next_event (eval at genAsyncOp (internal:core/01_core.js:181:14), <anonymous>:15:21)
    at Object.opAsync (internal:core/01_core.js:249:12)
    at WebSocket.[[[eventLoop]]] (internal:ext/websocket/01_websocket.js:405:44)

    at assert (internal:ext/web/00_infra.js:295:13)
    at asyncOpSanitizer (internal:cli/js/40_testing.js:233:13)
    at async resourceSanitizer (internal:cli/js/40_testing.js:378:7)
    at async Object.exitSanitizer [as fn] (internal:cli/js/40_testing.js:435:9)
    at async runTest (internal:cli/js/40_testing.js:840:7)
    at async runTests (internal:cli/js/40_testing.js:1098:22)

 FAILURES 

SurrealDB => https://deno.land/std@0.185.0/testing/_test_suite.ts:191:10

FAILED | 0 passed | 1 failed (1 step) (80ms)

error: Test failed
```

**Comment by kearfy** [comment]
Thanks for the write up, that really helps. I just confirmed that this will be fixed by #95.
I did a massive refactor there and opening/closing the socket has also been majorly improved there.

<img width="757" alt="image" src="https://user-images.githubusercontent.com/17960250/236410987-cc1c86f6-94d9-47b9-9bce-2710eb86b5f3.png">

I will soon be improving the tests as it's currently implemented a little bit hacky, will also take this into consideration (to add it as a test). Thank you!

**Comment by finalclass** [comment]
That's great news:) Thanks

**Comment by finalclass** [comment]
I've checked this test on the new version. There are no leaking async ops which is great. 

However for some reason db closing takes about 5 seconds. Is there any way to speed this up?

**Comment by kearfy** [comment]
I've been wondering about that too, not too sure about that...
Difficulty might be that the WebSocket implementation is different basically everywhere, but I'll have a look at it soon!
